### ISSUE TITLE
[mapnik-3] Postgis datasource

### ISSUE THREAD

**Issue by rochoa** [CartoDB/mapnik#17]
- [x] Review postgis datasource and see how different cdb is from master.
 - [x] Validate TWKB changes are fully merged into master, otherwise fork and apply.

**Comment by jgoizueta** [comment]
# CARTO Mapnik version overview

The Mapnik version used by CARTO is a [prepackaged one](https://github.com/CartoDB/mapnik-packaging) currently based on this fork's [`2.3.x.cartodb`](https://github.com/CartoDB/mapnik/tree/2.3.x.cartodb) branch which derives from upstreams' [`2.3.x`](https://github.com/mapnik/mapnik/tree/2.3.x).

Version 3 of Mapnik is being developed in branch [`v3.0.x`](https://github.com/mapnik/mapnik/tree/v3.0.x)

More information about compiling Mapnik is available [here](https://github.com/CartoDB/mapnik/pull/16).

# Existing changes in 2.3.x.cartob

Our fork contains modifications in three areas:

* TWKB support in the PostGIS datasource (`plugins/input/postgis/`)
* PostGIS raster dataset fixes (`plugins/input/pgraster`)
* Other changes (only to `src/agg/process_polygon_symbolizer.cpp`)

Here's a summary of the situation of these changes:

## TWKB

TWKB-releated includes the following:

* 2015-07 - TWKB by pramsey https://github.com/CartoDB/mapnik/pull/2
* 2015-10 - (twkb_rounding_adjustment_, remove repeated, simplify...) https://github.com/CartoDB/mapnik/pull/5
* 2015-10 - ST_SnaptoGrid fix by rochoa https://github.com/CartoDB/mapnik/pull/7
* 2015-10 - add ST_ClipByBox2D to TWKB by rochoa https://github.com/CartoDB/mapnik/pull/8
* 2015-11 - fix TWKB issue by dgaubert https://github.com/CartoDB/mapnik/pull/10
* 2016-01 - (profiling) by pramsey https://github.com/CartoDB/mapnik/pull/13

Almost all of this was added upstream on 2016-03: https://github.com/mapnik/mapnik/issues/3355

So this is now upstream in `master` and `v3.0.x`, save that code style is adapted and some reorganization (`plugins/input/postgis/postgis_utils.cpp` -> `src/twkb.cpp`). It is not in `2.3.x`.

There is one exception, though: the profiling modification https://github.com/CartoDB/mapnik/pull/13 is not present upstream.

## pgraster

* 2015-07 - fixes by pramsey https://github.com/CartoDB/mapnik/pull/3
* 2016-06 - (don't fall back to base table) by rtorre https://github.com/CartoDB/mapnik/pull/15

~~The first changeset is not present upstream~~, except for a part of it (commenting out some code) which was done here: https://github.com/mapnik/mapnik/commit/15a2acf0d59d761d0f428106e92393dae14916c9)
EDIT: I was wrong: the changes are [here](https://github.com/mapnik/mapnik/commit/d144f97f4e5c667b86c16ee4bfc0113d00afa81e), [here](https://github.com/mapnik/mapnik/commit/c3b8bbe511370169878291a7e76b8fa14b97aa3f), [here](https://github.com/mapnik/mapnik/commit/f72baaade1ea8c4f32da1e7a955afb84a3234c01) and [here](https://github.com/mapnik/mapnik/commit/ca5f92ab03ccec377f756fd89d586fdbeb29011d) but need to check if there are relevant differences.

The second changeset is present in `master` and `v3.0.x` upstream: https://github.com/mapnik/mapnik/pull/3424 (but not in `2.3.x`)

Note there was some confusion regarding the base table fix (about this change having been removed from our fork), seemingly because we had a previous PR #14 which was substituted by #15). UPDATE: I think I got confused by [this revert](https://github.com/CartoDB/mapnik/commit/996ea2d2fa61597303fd7d59471c32fc78eb0d4c) which is actually missing upstream (but not raster-related).

## Polygon fill fix

* 2016-01 - fix by pramsey https://github.com/CartoDB/mapnik/pull/12 reverted on 2016-06 (#https://github.com/CartoDB/mapnik/commit/996ea2d2fa61597303fd7d59471c32fc78eb0d4c)

The is present is upstream in `master`, `v3.0.x` and it hasn't been reverted there.

**Comment by rochoa** [comment]
About the profiling changes, the `RENDERING_STATS` build option was removed some time out, as per https://github.com/mapnik/mapnik/issues/780. A new issue was created, replacing the previous one, that lists the required developments: 
https://github.com/mapnik/mapnik/issues/1956.

So we could ignore any change related to profiling.

**Comment by jgoizueta** [comment]
So the situation is:

* TWKB: since profiling is not relevant, by looking a the code it seems all our needs are in master/3.x    We should now perform some test with the 3.x branch to be sure (since there's some code reorganization).
* pgraster: ~~we should push the fixes in #3 upstream~~ (i.e. port them to master as submit a PR) EDIT: checking if there's actually anything that needs to be pushed
* polygon fill fix: ~~nothing to do~~ EDIT: We're missing commit https://github.com/CartoDB/mapnik/commit/996ea2d2fa61597303fd7d59471c32fc78eb0d4c upstream. Note that the fix had been implementedupstream since 2013-10 (https://github.com/mapnik/mapnik/commit/2eaf6a1ead673a83cd92f7d84fee7d2db1d77aa0), but not in the 2.3.x branches/releases.

If TWKB works as expected and we succeed in pushing the polygon fill revert we could have our next package based directly on upstream 3.0

**Comment by jgoizueta** [comment]
Regarding pgraster #3 the situation isn't very clear: there's a number of commits that seem to address the same problems as #3 but with differences in implementation:

* https://github.com/mapnik/mapnik/commit/d144f97f4e5c667b86c16ee4bfc0113d00afa81e
* https://github.com/mapnik/mapnik/commit/ca5f92ab03ccec377f756fd89d586fdbeb29011d
* https://github.com/mapnik/mapnik/commit/c3b8bbe511370169878291a7e76b8fa14b97aa3f
* https://github.com/mapnik/mapnik/commit/f72baaade1ea8c4f32da1e7a955afb84a3234c01
* https://github.com/mapnik/mapnik/commit/cdc800b0869afd6262cad0e4d8ff12694b0971f8

I'll use the [original issue](https://github.com/mapnik/mapnik/issues/2661) data to check if master/3.x has actually fixed that case

**Comment by jgoizueta** [comment]
# Checking #3 

To check if the #3 fixes are properly working master/v3.0.x upstream I've done the following to verify that the issues mentioned in https://github.com/mapnik/mapnik/issues/2661 (which where the motivation for #3) are fixed in v3.0.x

I've compiled locally branch [`v3.0.x`](https://github.com/mapnik/mapnik/tree/v3.0.x) with Python bindings.

I've downloaded the 8-bit and 16-bit raster files from the ticket:
* http://firefly.ibk.se/~racer/demui8.tif
* http://firefly.ibk.se/~racer/demui16.tif

I've imported them in PostGIS:

```
raster2pgsql -I -t 128x128 -s 3857 data/demui8.tif | psql -U USER DB
raster2pgsql -I -t 128x128 -s 3857 data/demui16.tif | psql -U USER DB
```

I've prepared map configuration files for Mapnik from the snippet in the ticket to render each of the raster layers from PostGIS:

raster8.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
    <Parameters>
        <Parameter name="name"><![CDATA[8-bit Raster]]></Parameter>
        <Parameter name="description"><![CDATA[Testing, Testing...]]></Parameter>
    </Parameters>
    <Style name="style" filter-mode="first">
        <Rule>
            <RasterSymbolizer opacity="1" />
        </Rule>
    </Style>
    <Layer name="layer" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
        <StyleName>style</StyleName>
        <Datasource>
            <Parameter name="type"><![CDATA[pgraster]]></Parameter>
            <Parameter name="table"><![CDATA[(select rast from demui8) as dem]]></Parameter>
            <Parameter name="key_field"><![CDATA[]]></Parameter>
            <Parameter name="extent_cache"><![CDATA[auto]]></Parameter>
            <Parameter name="extent"><![CDATA[1156370.42574902,7437535.6778537,2686825.1237811,10772410.4667944]]></Parameter>
            <Parameter name="dbname"><![CDATA[DB]]></Parameter>
            <Parameter name="host"><![CDATA[localhost]]></Parameter>
            <Parameter name="port"><![CDATA[5432]]></Parameter>
            <Parameter name="user"><![CDATA[USER]]></Parameter>
            <Parameter name="password"><![CDATA[PASSWORD]]></Parameter>
        </Datasource>
    </Layer>
</Map>
```

raster16.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
    <Parameters>
        <Parameter name="name"><![CDATA[16-bit Raster]]></Parameter>
        <Parameter name="description"><![CDATA[Testing, Testing...]]></Parameter>
    </Parameters>
    <Style name="style" filter-mode="first">
        <Rule>
            <RasterSymbolizer opacity="1" />
        </Rule>
    </Style>
    <Layer name="layer" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
        <StyleName>style</StyleName>
        <Datasource>
            <Parameter name="type"><![CDATA[pgraster]]></Parameter>
            <Parameter name="table"><![CDATA[(select rast from demui16) as dem]]></Parameter>
            <Parameter name="key_field"><![CDATA[]]></Parameter>
            <Parameter name="extent_cache"><![CDATA[auto]]></Parameter>
            <Parameter name="extent"><![CDATA[1156370.42574902,7437535.6778537,2686825.1237811,10772410.4667944]]></Parameter>
            <Parameter name="dbname"><![CDATA[DB]]></Parameter>
            <Parameter name="host"><![CDATA[localhost]]></Parameter>
            <Parameter name="port"><![CDATA[5432]]></Parameter>
            <Parameter name="user"><![CDATA[USER]]></Parameter>
            <Parameter name="password"><![CDATA[PASSWORD]]></Parameter>
        </Datasource>
    </Layer>
</Map>
```

I've written and executed this script to render the maps:

```python
import mapnik

coords = ((1673798.306, 8287516.642), (1679641.214, 8299698.926))

def render_test(xml, png):
    m = mapnik.Map(800, 800)
    mapnik.load_map_from_string(m, xml)
    bbox = mapnik.Envelope(mapnik.Coord(*coords[0]), mapnik.Coord(*coords[1]))
    print bbox
    m.zoom_to_box(bbox)
    mapnik.render_to_file(m, png, 'png')

for bits in ['8', '16']:
    with open('raster'+bits+'.xml', 'r') as xmlFile: xmlMap = xmlFile.read()
    render_test(xmlMap, 'raster'+bits+'.png')

print "Done"
```

# Results

The resulting maps are free for the problems mentioned in the ticket: nodata areas are transparent and the banding due to 16-bit values wrapped to 8-bits doesn't happen:

raster16.png:
![raster_8](https://cloud.githubusercontent.com/assets/5909/22070326/dffe60a0-dd9b-11e6-9a7b-51796e648154.png)

raster8.png:
![raster_16](https://cloud.githubusercontent.com/assets/5909/22070330/e49a0fb0-dd9b-11e6-9de3-78c1746d57e9.png)

**Comment by jgoizueta** [comment]
# Checking TWKB

I've used Mapnik configuration file extracted from a CARTO map to compare the current CARTO tiler behaviour with a python script using Mapnik v3.0.x and check:

a) whether the SQL queries that the Mapnik performs to PG use TWKB just like the tiler when the xml configuration has `twkb_encoding = true`. (i.e. TWKB is being used)

b) whether the rendered map looks like the one from the tiler (i.e. if the TWKB coordinates are handled properly)

Both checks have been succesful.

The first line shows a query from the tiler with Mapnik 2 and the second one one from the test script with Mapnik 3:

```
SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints("the_geom_webmercator",10),10,true),-1) AS geom FROM (SELECT * FROM educacion_4) as cdbq WHERE "the_geom_webmercator" && ST_MakeEnvelope(-435385.3131123646,4926213.598923039,-406033.4942508549,4955565.417784547,3857) LIMIT 65535
SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints("the_geom_webmercator",10),10,true),-1) AS geom FROM (SELECT * FROM educacion_4) as cdbq WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-435385.3131123661 4926213.598923037,-406033.4942508509 4955565.417784553)'::box3d, 3857) LIMIT 65535
````

This image has been generated by the tiler:

![check_771](https://cloud.githubusercontent.com/assets/5909/22076922/6a568294-ddb2-11e6-8c6a-606ea66d5b34.png)

This one is generated by the script:

![points](https://cloud.githubusercontent.com/assets/5909/22076948/814be1c4-ddb2-11e6-92aa-062ce08a63ec.png)

(for some reason it looks smoother, but the points seem identically placed)

**Comment by jgoizueta** [comment]
Update: reviewing again the commits that are not upstream I've realized that I had missed that [this revert](https://github.com/CartoDB/mapnik/commit/996ea2d2fa61597303fd7d59471c32fc78eb0d4c) of the polygon fix is not upstream. I've updated some comments above to reflect it.

So far (I still have to finish my review) this seems the only thing missing.

**Comment by jgoizueta** [comment]
# Checking Polygon Fill revert

## Timeline:

* 2013-10 https://github.com/CartoDB/mapnik/commit/2eaf6a1ead673a83cd92f7d84fee7d2db1d77aa0
  (polygon filling uses fill_even_odd rule in agg/process_polygon_symbolizer and other places)
  This never got to 2.3.x; It is in master and v3.0.x

* 2016-01  #11 
  To fix #11 pramsey introduces equivalent change (only in agg/process_polygon_symbolizer)
  in our 2.3.x.cartodb branch

* 2016-06 https://github.com/CartoDB/mapnik/commit/996ea2d2fa61597303fd7d59471c32fc78eb0d4c
  For our release, rafatower removes that change from our branch,  because of tilelive-mapnik failing tests and some observed problem related to buffer-size
  > The conclusion is that the reverted patch may affect the size of the buffers depending on the clipping options

## Situation

The releases from our fork never got this change which is in v3.0x.

The current version of tilelive-mapnik (master) is passing those tests using Mapnik 3.0.12
which has the change:

```
  Render
    ✓ getTile() override format
    getTile()
      ✓ validates (115ms)
    getTile() with XML string
      ✓ validates (119ms)
```

(it passes all tests)

There's no apparent problem with the change that we removed from our repo. That change has been present upstream for a long time, and we removed it before our release just out of caution. I think we shouldn't worry about this anymore.

**Comment by jgoizueta** [comment]
Having reviewed the changes in our fork that are not upstream my conclusion is that we don't rely on any behaviour not present in the main repo in master or v3.0.x so we can base our future 3.x releases on it.
cc @rochoa

**Comment by rochoa** [comment]
That's super good news @jgoizueta.

Thanks a lot for going through all these changes, and doing a such a nice summary 👍 .

**Comment by dgaubert** [comment]
Impressive work @jgoizueta 

As @rochoa said, thanks for researching ;) that's a really great news.

I've been testing our stack with Mapnik v3.x directly from upstream for weeks. I've updated from upstream our forked projects and applied minor changes when needed: 
 - https://github.com/CartoDB/tilelive-mapnik/pull/5
 - https://github.com/CartoDB/abaculus/pull/4
 - [CartoDB/node-canvas#1.6.2-cdb2](https://github.com/CartoDB/node-canvas/releases/tag/1.6.2-cdb2)
 - https://github.com/CartoDB/grainstore/pull/119
 - [CartoDB/Windshaft#mapnik-migration](https://github.com/CartoDB/Windshaft/tree/mapnik-migration). 

It hasn't came up anything that we had to be worried yet. Integration has gone smooth so far and we have a [branch of the tiler](https://github.com/CartoDB/Windshaft-cartodb/tree/node-v6) which is actually working with Mapnik v3 and Node v6. I think we can go ahead with the migration and close this issue.

Thanks a lot @jgoizueta, much appreciated your help! ❤️
